on:
  release:
    types: [published]
    branches:
      - master

env:
  GITHUB_WORKSPACE: "~/app"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Setup Node
      - name: NPM Cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
      - run: npm install
        name: Install NPM Dependencies
      - run: npm run build
        name: NPM Build
      - run: npm run lint
        name: Run Linter
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        name: Deploy Files
        with:
          server: ${{ secrets.url }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: "./dist/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.well-known/**
            **/cgi-bin/**
